In [1]:
import numpy as np

class Linear:
    def __init__(self, input_dim, output_dim):
        # Initialize weights randomly and biases to zero
        # We divide by sqrt(input_dim) to keep starting variance small (Xavier/He initialization)
        self.W = np.random.randn(input_dim, output_dim) / np.sqrt(input_dim)
        self.b = np.zeros(output_dim)

        # We will store X here during the forward pass so we can use it in the backward pass
        self.X_cache = None

        # Gradients will be stored here
        self.dW = None
        self.db = None

    def forward(self, X):
        """
        X shape: (batch_size, input_dim)
        Returns: Z shape (batch_size, output_dim)
        """
        # Save X for the backward pass
        self.X_cache = X

        # TODO: Calculate Z = XW + b
        Z = X @ self.W + self.b

        return Z

    def backward(self, dZ):
        """
        dZ shape: (batch_size, output_dim)
        Returns: dX shape (batch_size, input_dim)
        """
        X = self.X_cache

        # TODO: Calculate dW, db, and dX based on the formulas above
        self.dW = X.T @ dZ
        self.db = np.sum(dZ, axis=0)
        dX = dZ @ self.W.T

        return dX

In [2]:
def naive_softmax(X):
    exps = np.exp(X)
    return exps/np.sum(exps, axis=-1, keepdims=True)

## Reduction Operation in Numpy

A reduction is an operation that aggregates values along an axis and reduces the dimensionality of the array.

##### **Let's start with a array of 2 dimension**
**tips**: a 2 dimension array has one dimension array as its elements. One dimension array are just normal array or list.

In [28]:
arr = [
    [1, 2, 1],
    [3, 2, 4]
]

arr = np.array(arr) # its dim = 2, shape=(2, 2)

print(arr.ndim) # its dim = 2

print(arr.shape) # its shape=(2,2)


2
(2, 3)


#### Using sum 

In [29]:
new_arr = np.sum(arr, axis=0)
print(f"The original array: \n {arr}")
print(f"The aggregated array: \n{new_arr}")
print(f"arr dimension: {new_arr.ndim}")
print(f"arr shape: {new_arr.shape}")

The original array: 
 [[1 2 1]
 [3 2 4]]
The aggregated array: 
[4 4 5]
arr dimension: 1
arr shape: (3,)


In [30]:
new_arr = np.sum(arr, axis=1)
print(f"The original array: \n {arr}")
print(f"The aggregated array: ]n {new_arr}")
print(f"arr dimension: {new_arr.ndim}")
print(f"arr shape: {new_arr.shape}")


The original array: 
 [[1 2 1]
 [3 2 4]]
The aggregated array: ]n [4 9]
arr dimension: 1
arr shape: (2,)


In both of above example we can see that axis determines how the axis of aggregation. `axis=0` makes the x-axis collapse and the shape of x-axis is lost. Similarly, `axis=1` makes the y-axis values collapse and the shape of the y-axis is lost.


In [32]:
arr = [[[1, 2], [1, 2], [4, 3]], [[2, 5], [5, 7], [3, 1]]]

arr = np.array(arr)

print(arr.shape)

(2, 3, 2)


In [35]:
val_1 = np.sum(arr, axis=0, keepdims=False)
val_2 = np.sum(arr, axis=0, keepdims=True)
print(f"Original array: {arr}")
print(f"New array 1: {val_1}")
print(f"New array 2: {val_2}")

print(f"New array 1 shape: {val_1.shape}")
print(f"New array 2 shape: {val_2.shape}")


Original array: [[[1 2]
  [1 2]
  [4 3]]

 [[2 5]
  [5 7]
  [3 1]]]
New array 1: [[3 7]
 [6 9]
 [7 4]]
New array 2: [[[3 7]
  [6 9]
  [7 4]]]
New array 1 shape: (3, 2)
New array 2 shape: (1, 3, 2)


`keepdims=True` makes sure the original shape of the array isn't lost even after collapsing the values along the axis