**Nested array**: Arrays that have arrays as their elements

**Dimension**: Dimension in arrays is one level of array depth.

**0-D array**:
- e.g. 2, 45
- also known as scalars

**1-D array**:
- [1, 2, 3, 4, 5]
- uni-dimensional array
- has 0-D array as its elements.

**2-D array**:
- [[1, 2, 3], [2, 5, 7]]
- Bi-dimensional array
- has 1-D array as its elements

**3-D array**:
- [ [[1, 2, 3], [2, 5, 7]], [[1, 2, 5], [3, 5, 9]] ]
- has 2-D array as its elements
- (2, 2, 3)

In [1]:
import numpy as np

In [2]:
a = np.array(42)
b = np.array([2, 3, 5, 6, 8])
c = np.array([[8, 9, 10], [2, 6, 9]])

d = np.array([ [[2, 5, 6], [5, 6, 7 ]], [[3, 5, 2], [4, 2, 7]]])

In [6]:
d.ndim

3

In [3]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
a = np.array([1, 2, 3, 4, 5], ndmin=4)
a = np.array([1, 2, 3, 4, 5], ndmin=5)

In [10]:
a

array([[[[[1, 2, 3, 4, 5]]]]])

In [15]:
import numpy as np

class Linear:
    def __init__(self, input_dim, output_dim):
        # Initialize weights randomly and biases to zero
        # We divide by sqrt(input_dim) to keep starting variance small (Xavier/He initialization)
        self.W = np.random.randn(input_dim, output_dim) / np.sqrt(input_dim)
        self.b = np.zeros(output_dim)

        # We will store X here during the forward pass so we can use it in the backward pass
        self.X_cache = None

        # Gradients will be stored here
        self.dW = None
        self.db = None

    def forward(self, X):
        """
        X shape: (batch_size, input_dim)
        Returns: Z shape (batch_size, output_dim)
        """
        # Save X for the backward pass
        self.X_cache = X

        # TODO: Calculate Z = XW + b
        Z = X @ self.W + self.b

        return Z

    def backward(self, dZ):
        """
        dZ shape: (batch_size, output_dim)
        Returns: dX shape (batch_size, input_dim)
        """
        X = self.X_cache

        # TODO: Calculate dW, db, and dX based on the formulas above
        self.dW = X.T @ dZ
        self.db = np.sum(dZ, axis=0)
        dX = dZ @ self.W.T

        return dX

In [17]:
# stable_softmax()

def naive_softmax(X):
  exps = np.exp(X)
  return exps/np.sum(exps, axis=-1, keepdims=True)




In [18]:
naive_softmax([1000, 1001, 1002])

/tmp/ipython-input-164/1824532343.py:4: RuntimeWarning: overflow encountered in exp
  exps = np.exp(X)
/tmp/ipython-input-164/1824532343.py:5: RuntimeWarning: invalid value encountered in divide
  return exps/np.sum(exps, axis=-1, keepdims=True)


array([nan, nan, nan])

In [23]:
def stable_softmax(X):
  exps = np.exp(X - np.max(X, axis=-1, keepdims=True))
  return exps/np.sum(exps, axis=-1, keepdims=True)

In [24]:
stable_softmax([1000, 1001, 1002])

array([0.09003057, 0.24472847, 0.66524096])